# Generated by Django 4.2.25 on 2025-11-13 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import landing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('preferred_language', models.CharField(default='es', max_length=10)),
                ('preferred_theme', models.CharField(choices=[('system', 'Sistema'), ('dark', 'Oscuro'), ('light', 'Claro')], default='system', max_length=12)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('notification_level', models.CharField(default='smart', max_length=24)),
                ('telemetry_alerts', models.BooleanField(default=True)),
                ('ingest_token', models.CharField(default=landing.models._generate_ingest_token, editable=False, max_length=64, unique=True)),
                ('favorite_robot', models.CharField(blank=True, max_length=64)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
