# Generated by Django 4.2.26 on 2025-12-03 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_order_transaction_orderitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('starter', 'Starter - €19.99/mes'), ('pro', 'Pro - €59.99/mes'), ('elite', 'Elite - €199.99/mes')], default='starter', max_length=20, verbose_name='Nivel')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('pending', 'Pendiente de pago'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renovación automática')),
                ('payment_tx_signature', models.CharField(blank=True, max_length=88, verbose_name='Firma de transacción de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (cm)')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino'), ('non_binary', 'No binario'), ('prefer_not_say', 'Prefiero no decir')], max_length=20, verbose_name='Género')),
                ('fitness_goals', models.JSONField(blank=True, default=list, verbose_name='Objetivos de fitness')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biografía')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de perfil')),
                ('solana_public_key', models.CharField(blank=True, help_text='Dirección de wallet Solana (base58)', max_length=44, verbose_name='Llave pública Solana')),
                ('wallet_verified', models.BooleanField(default=False, verbose_name='Wallet verificada')),
                ('wallet_connected_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de conexión de wallet')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Puntos')),
                ('rank', models.CharField(choices=[('novato', 'Novato'), ('aprendiz', 'Aprendiz'), ('guerrero', 'Guerrero'), ('maestro', 'Maestro'), ('leyenda', 'Leyenda')], default='novato', max_length=20, verbose_name='Rango')),
                ('profile_completion', models.PositiveSmallIntegerField(default=0, verbose_name='Completitud del perfil (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_character', models.ForeignKey(blank=True, help_text='Debe ser un item del inventario del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='shop.product', verbose_name='Personaje activo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_signature', models.CharField(help_text='Transaction signature de Solana', max_length=88, unique=True, verbose_name='Firma de transacción')),
                ('amount_sol', models.DecimalField(decimal_places=9, max_digits=18, verbose_name='Cantidad (SOL)')),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad (USD)')),
                ('purpose', models.CharField(choices=[('subscription', 'Suscripción'), ('purchase', 'Compra de producto'), ('tip', 'Propina/Donación')], max_length=20, verbose_name='Propósito')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de verificación'), ('verified', 'Verificada'), ('failed', 'Fallida'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='Estado')),
                ('from_wallet', models.CharField(blank=True, max_length=44, verbose_name='Wallet origen')),
                ('to_wallet', models.CharField(blank=True, help_text='Wallet de Croody', max_length=44, verbose_name='Wallet destino')),
                ('block_time', models.DateTimeField(blank=True, null=True, verbose_name='Tiempo de bloque')),
                ('verification_data', models.JSONField(blank=True, default=dict, verbose_name='Datos de verificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='shop.product', verbose_name='Producto')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.subscription', verbose_name='Suscripción')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Transacción de wallet',
                'verbose_name_plural': 'Transacciones de wallet',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_wa_user_id_cb63fa_idx'), models.Index(fields=['tx_signature'], name='accounts_wa_tx_sign_bdc38e_idx'), models.Index(fields=['status', 'created_at'], name='accounts_wa_status_6a4c2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de adquisición')),
                ('transaction_signature', models.CharField(blank=True, help_text='Signature de la transacción Solana', max_length=88, verbose_name='Firma de transacción')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Descargas')),
                ('is_gift', models.BooleanField(default=False, verbose_name='Es regalo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='shop.product', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Item de inventario',
                'verbose_name_plural': 'Items de inventario',
                'ordering': ['-acquired_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
