# Generated by Django 4.2.27 on 2025-12-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firebase_uid',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador unico de Firebase Auth para sincronizacion con Buddy app', max_length=128, null=True, unique=True, verbose_name='Firebase UID'),
        ),
    ]
